"use client"

import { createContext, useContext, useState, type ReactNode, useCallback, useEffect } from "react"

type Language = "en" | "ru"

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

interface LanguageProviderProps {
  children: ReactNode
}

type TranslationDictionary = {
  [key: string]: string
}

type Translations = {
  en: TranslationDictionary
  ru: TranslationDictionary
}

const LANGUAGE_STORAGE_KEY = "gsom-timetable-language"

const translations: Translations = {
  en: {
    "home.title": "GSOM Timetable",
    "home.subtitle": "Select your degree, program, year and group",
    "timetable.program": "Timetable",
    "timetable.group": "Group",
    "timetable.return": "Return to Selection",
    "timetable.thisWeek": "This Week",
    "timetable.noClasses": "No classes scheduled for this day.",
    "language.switch": "Switch Language",
    "room.label": "Room",
    "footer.feedback": "Found a mistake or want to suggest an improvement?",
    "footer.gsomStudent": "Developed by a GSOM Student",
    "footer.telegramMessage": "Send a message via Telegram",
    "programs.internationalManagement": "International Management",
    "programs.management": "Management",
    "programs.publicAdministration": "Public Administration",
    "programs.businessAnalytics": "Business Analytics and Big Data",
    "programs.smartCityManagement": "Smart City Management",
    "programs.corporateFinance": "Corporate Finance",
    "degree.bachelor": "Bachelor's",
    "degree.master": "Master's",
    "year.enrollment": "Year of Enrollment",
    "auth.login.title": "GSOM Elective Platform",
    "auth.login.description": "Enter your credentials to access your account",
    "auth.login.email": "Email",
    "auth.login.password": "Password",
    "auth.login.button": "Login",
    "auth.login.demoText": "For demo purposes, you can also:",
    "auth.login.studentDemo": "Student Demo",
    "auth.login.managerDemo": "Manager Demo",
    "auth.login.adminDemo": "Admin Demo",
    "auth.login.noAccount": "Don't have an account?",
    "auth.login.signUp": "Sign up",
    "auth.signup.title": "GSOM Elective Platform",
    "auth.signup.description": "Create a new account with your university email",
    "auth.signup.email": "Email",
    "auth.signup.emailHint": "Must end with @student.spbu.ru or @gsom.spbu.ru",
    "auth.signup.name": "Full Name",
    "auth.signup.degree": "Degree",
    "auth.signup.program": "Program",
    "auth.signup.year": "Year",
    "auth.signup.group": "Group",
    "auth.signup.password": "Password",
    "auth.signup.button": "Sign Up",
    "auth.signup.hasAccount": "Already have an account?",
    "auth.signup.login": "Login",
    "auth.signup.selectDegree": "Select degree",
    "auth.signup.selectProgram": "Select program",
    "auth.signup.selectYear": "Select year",
    "auth.signup.selectGroup": "Select group",
    "auth.error.invalidEmail": "Email must end with @student.spbu.ru or @gsom.spbu.ru",
    "auth.error.incompleteFields": "Please complete all required fields",
    dashboard: "Dashboard",
    courseSelection: "Course Selection",
    exchangeSelection: "Exchange Selection",
    logout: "Logout",

    // Student Dashboard
    "student.dashboard.title": "Dashboard",
    "student.dashboard.requiredElectives": "Required Electives",
    "student.dashboard.selectedElectives": "Selected Electives",
    "student.dashboard.pendingSelections": "Pending Selections",
    "student.dashboard.courses": "courses",
    "student.dashboard.exchange": "exchange programs",
    "student.dashboard.yourInfo": "Your Information",
    "student.dashboard.academicDetails": "Your academic details",
    "student.dashboard.name": "Name",
    "student.dashboard.degree": "Degree",
    "student.dashboard.program": "Program",
    "student.dashboard.yearEnrollment": "Year of Enrollment",
    "student.dashboard.group": "Group",
    "student.dashboard.email": "Email",
    "student.dashboard.upcomingDeadlines": "Upcoming Deadlines",
    "student.dashboard.importantDates": "Important dates for elective selections",
    "student.dashboard.daysLeft": "days left",

    // Student Courses
    "student.courses.title": "Course Selection",
    "student.courses.subtitle": "Browse and select elective courses available in the semester for your program",
    "student.courses.deadline": "Deadline",
    "student.courses.courses": "Courses",
    "student.courses.limit": "Limit",
    "student.courses.selected": "Selected",
    "student.courses.view": "View",
    "student.courses.noSelection": "No Selection",
    "student.courses.comingSoon": "Coming Soon",
    "student.courses.open": "Open",
    "student.courses.limited": "Limited",
    "student.courses.selectCourses": "Select your elective courses for this semester",
    "student.courses.selectionProgress": "Selection Progress",
    "student.courses.selectedOutOf": "You have selected",
    "student.courses.allowedCourses": "allowed courses",
    "student.courses.maxSelections": "You've reached the maximum number of selections",
    "student.courses.canSelectMore": "You can select",
    "student.courses.moreCourse": "more course",
    "student.courses.moreCourses": "more courses",
    "student.courses.selectionApproved": "Selection Approved",
    "student.courses.selectionApprovedDesc":
      "Your selection for these elective courses has been approved. You can view your selected courses below.",
    "student.courses.selectionPending": "Selection Pending",
    "student.courses.selectionPendingDesc":
      "Your selection for these elective courses is pending approval. You can still modify your selection until the deadline.",
    "student.courses.selectionPeriodActive": "Selection Period Active",
    "student.courses.selectionPeriodDesc": "You can select up to",
    "student.courses.until": "until",
    "student.courses.viewDescription": "View Description",
    "student.courses.select": "Select",
    "student.courses.updateSelection": "Update Selection",
    "student.courses.confirmSelection": "Confirm Selection",
    "student.courses.confirmYourSelection": "Confirm Your Selection",
    "student.courses.reviewSelection":
      "Please review your selection and enter your full name to authorize this submission.",
    "student.courses.selectedCourses": "Selected Courses",
    "student.courses.credits": "credits",
    "student.courses.yourFullName": "Your Full Name",
    "student.courses.toAuthorize": "to authorize",
    "student.courses.enterFullName": "Enter your full name",
    "student.courses.submitting": "Submitting...",
    "student.courses.submitSelection": "Submit Selection",
    "student.courses.courseDescription": "Course Description",
    "student.courses.close": "Close",
    "student.courses.removeSelection": "Remove Selection",
    "student.courses.selectCourse": "Select Course",

    // Student Exchange
    "student.exchange.title": "Exchange Program Selection",
    "student.exchange.subtitle": "Browse and select exchange universities available for your program",
    "student.exchange.deadline": "Deadline",
    "student.exchange.universities": "Universities",
    "student.exchange.limit": "Limit",
    "student.exchange.selected": "Selected",
    "student.exchange.view": "View",
    "student.exchange.noSelection": "No Selection",
    "student.exchange.comingSoon": "Coming Soon",
    "student.exchange.open": "Open",
    "student.exchange.limited": "Limited",
    "student.exchange.selectUniversities": "Select your exchange universities for this semester",
    "student.exchange.selectionProgress": "Selection Progress",
    "student.exchange.selectedOutOf": "You have selected",
    "student.exchange.allowedUniversities": "allowed universities",
    "student.exchange.maxSelections": "You've reached the maximum number of selections",
    "student.exchange.canSelectMore": "You can select",
    "student.exchange.moreUniversity": "more university",
    "student.exchange.moreUniversities": "more universities",
    "student.exchange.selectionApproved": "Selection Approved",
    "student.exchange.selectionApprovedDesc":
      "Your selection for these exchange universities has been approved. You can view your selected universities below.",
    "student.exchange.selectionPending": "Selection Pending",
    "student.exchange.selectionPendingDesc":
      "Your selection for these exchange universities is pending approval. You can still modify your selection until the deadline.",
    "student.exchange.selectionPeriodActive": "Selection Period Active",
    "student.exchange.selectionPeriodDesc": "You can select up to",
    "student.exchange.until": "until",
    "student.exchange.viewDetails": "View Details",
    "student.exchange.select": "Select",
    "student.exchange.updateSelection": "Update Selection",
    "student.exchange.confirmSelection": "Confirm Selection",
    "student.exchange.confirmYourSelection": "Confirm Your Selection",
    "student.exchange.reviewSelection":
      "Please review your selection and enter your full name to authorize this submission.",
    "student.exchange.selectedUniversities": "Selected Universities",
    "student.exchange.yourFullName": "Your Full Name",
    "student.exchange.toAuthorize": "to authorize",
    "student.exchange.enterFullName": "Enter your full name",
    "student.exchange.submitting": "Submitting...",
    "student.exchange.submitSelection": "Submit Selection",
    "student.exchange.universityDescription": "University Description",
    "student.exchange.languageInstruction": "Language of Instruction",
    "student.exchange.availablePrograms": "Available Programs",
    "student.exchange.close": "Close",
    "student.exchange.visitWebsite": "Visit Website",
    "student.exchange.comingSoonDesc":
      "Exchange selection is not open yet. You can preview the available universities, but selection will be available starting",

    // Manager Dashboard
    "manager.dashboard.title": "Dashboard",
    "manager.dashboard.courseElectives": "Elective Packs",
    "manager.dashboard.totalCourseElectives": "Total course elective selections",
    "manager.dashboard.manageCourseElectives": "Manage Course Electives",
    "manager.dashboard.exchangePrograms": "Exchange Programs",
    "manager.dashboard.totalExchangePrograms": "Total exchange programs available",
    "manager.dashboard.manageExchangePrograms": "Manage Exchange Programs",
    "manager.dashboard.yourInformation": "Your Information",
    "manager.dashboard.managerDetails": "Program manager details",
    "manager.dashboard.name": "Name",
    "manager.dashboard.program": "Program",
    "manager.dashboard.degree": "Degree",
    "manager.dashboard.year": "Year",
    "manager.dashboard.email": "Email",
    "manager.dashboard.upcomingDeadlines": "Upcoming Deadlines",
    "manager.dashboard.importantDates": "Important dates for electives",
    "manager.dashboard.daysLeft": "days left",

    // Manager Electives
    "manager.electives.title": "Elective Packs",
    "manager.electives.subtitle": "Manage course and exchange elective selections",
    "manager.electives.courseElectives": "Course Electives",
    "manager.electives.exchangePrograms": "Exchange Programs",
    "manager.electives.create": "Create",
    "manager.electives.searchCourses": "Search course electives...",
    "manager.electives.searchExchange": "Search exchange programs...",
    "manager.electives.program": "Program",
    "manager.electives.allPrograms": "All Programs",
    "manager.electives.semester": "Semester",
    "manager.electives.allSemesters": "All Semesters",
    "manager.electives.status": "Status",
    "manager.electives.allStatus": "All Status",
    "manager.electives.active": "Active",
    "manager.electives.inactive": "Inactive",
    "manager.electives.draft": "Draft",
    "manager.electives.deadline": "Deadline",
    "manager.electives.courses": "Courses",
    "manager.electives.selections": "Selections",
    "manager.electives.createdBy": "Created by",
    "manager.electives.on": "on",
    "manager.electives.viewDetails": "View Details",
    "manager.electives.noCourseElectives": "No course elective packs found.",
    "manager.electives.createNewElectivePack": "Create New Elective Pack",
    "manager.electives.universities": "Universities",
    "manager.electives.noExchangePrograms": "No exchange programs found.",
    "manager.electives.createNewExchangeProgram": "Create New Exchange Program",
    "manager.electives.edit": "Edit",
    "manager.electives.exportData": "Export Data",
    "manager.exchangeBuilder.statementUpload": "Statement Upload",
    "manager.exchangeBuilder.uploadStatementFile": "Upload Statement File (PDF)",
    "manager.exchangeBuilder.statementDescription":
      "Upload a blank statement file that students will download, sign, and re-upload.",
    "student.statement.title": "Statement Form",
    "student.statement.description": "Download the statement, sign it, and upload the completed form",
    "student.statement.download": "Download",
    "student.statement.uploading": "Uploading...",
    "student.statement.fileUploaded": "File uploaded:",

    // Manager Exchange Details
    "manager.exchangeDetails.backToElectives": "Back to Electives",
    "manager.exchangeDetails.edit": "Edit",
    "manager.exchangeDetails.programDetails": "Program Details",
    "manager.exchangeDetails.selectionPeriod": "Selection Period",
    "manager.exchangeDetails.maxSelections": "Max Selections",
    "manager.exchangeDetails.universities": "universities",
    "manager.exchangeDetails.studentsEnrolled": "Students Enrolled",
    "manager.exchangeDetails.created": "Created",
    "manager.exchangeDetails.status": "Status",
    "manager.exchangeDetails.universitiesTab": "Universities",
    "manager.exchangeDetails.studentsTab": "Student Selections",
    "manager.exchangeDetails.name": "Name",
    "manager.exchangeDetails.location": "Location",
    "manager.exchangeDetails.language": "Language",
    "manager.exchangeDetails.enrollment": "Enrollment",
    "manager.exchangeDetails.studentSelections": "Student Selections",
    "manager.exchangeDetails.manageStudentSelections": "Manage student selections for this exchange program",
    "manager.exchangeDetails.searchStudents": "Search students...",
    "manager.exchangeDetails.export": "Export",
    "manager.exchangeDetails.group": "Group",
    "manager.exchangeDetails.selectionDate": "Selection Date",
    "manager.exchangeDetails.view": "View",
    "manager.exchangeDetails.actions": "Actions",
    "manager.exchangeDetails.approved": "Approved",
    "manager.exchangeDetails.pending": "Pending",
    "manager.exchangeDetails.rejected": "Rejected",
    "manager.exchangeDetails.approve": "Approve",
    "manager.exchangeDetails.reject": "Reject",
    "manager.exchangeDetails.studentDetails": "Student Selection Details",
    "manager.exchangeDetails.viewDetailsFor": "View details for",
    "manager.exchangeDetails.exchangeSelection": "'s exchange selection",
    "manager.exchangeDetails.studentInformation": "Student Information",
    "manager.exchangeDetails.id": "ID",
    "manager.exchangeDetails.email": "Email",
    "manager.exchangeDetails.program": "Program",
    "manager.exchangeDetails.selectedUniversities": "Selected Universities",
    "manager.exchangeDetails.selectionInformation": "Selection Information",
    "manager.exchangeDetails.date": "Date",
    "manager.exchangeDetails.close": "Close",
    "manager.status.draft": "Draft",
    "manager.status.published": "Published",
    "manager.status.closed": "Closed",
    "manager.status.archived": "Archived",
    "manager.courseDetails.title": "Course Details",
    "manager.courseDetails.backToElectives": "Back to Electives",
    "manager.courseDetails.edit": "Edit",
    "manager.courseDetails.programDetails": "Program Details",
    "manager.courseDetails.selectionPeriod": "Selection Period",
    "manager.courseDetails.maxSelections": "Max Selections",
    "manager.courseDetails.courses": "courses",
    "manager.courseDetails.studentsEnrolled": "Students Enrolled",
    "manager.courseDetails.created": "Created",
    "manager.courseDetails.status": "Status",
    "manager.courseDetails.coursesTab": "Courses",
    "manager.courseDetails.studentsTab": "Student Selections",
    "manager.courseDetails.coursesInProgram": "Courses in this Program",
    "manager.courseDetails.name": "Name",
    "manager.courseDetails.professor": "Professor",
    "manager.courseDetails.credits": "Credits",
    "manager.courseDetails.enrollment": "Enrollment",
    "manager.courseDetails.studentSelections": "Student Selections",
    "manager.courseDetails.manageStudentSelections": "Manage student selections for this elective program",
    "manager.courseDetails.searchStudents": "Search students...",
    "manager.courseDetails.export": "Export",
    "manager.courseDetails.group": "Group",
    "manager.courseDetails.selectionDate": "Selection Date",
    "manager.courseDetails.view": "View",
    "manager.courseDetails.actions": "Actions",
    "manager.courseDetails.studentDetails": "Student Selection Details",
    "manager.courseDetails.viewDetailsFor": "View details for",
    "manager.courseDetails.courseSelection": "'s course selection",
    "manager.courseDetails.studentInformation": "Student Information",
    "manager.courseDetails.id": "ID",
    "manager.courseDetails.email": "Email",
    "manager.courseDetails.program": "Program",
    "manager.courseDetails.selectedCourses": "Selected Courses",
    "manager.courseDetails.selectionInformation": "Selection Information",
    "manager.courseDetails.date": "Date",
    "manager.courseDetails.close": "Close",
    "manager.courseBuilder.title": "Create Elective Course Selection",
    "manager.courseBuilder.draft": "Draft",
    "manager.courseBuilder.step1": "Basic Information",
    "manager.courseBuilder.step2": "Add Courses",
    "manager.courseBuilder.step3": "Review & Publish",
    "manager.courseBuilder.step": "Step",
    "manager.courseBuilder.of": "of",
    "manager.courseBuilder.courseInfo": "Course Selection Information",
    "manager.courseBuilder.semester": "Semester",
    "manager.courseBuilder.year": "Year",
    "manager.courseBuilder.namePreview": "Course Selection Name Preview",
    "manager.courseBuilder.selectionRules": "Selection Rules",
    "manager.courseBuilder.maxSelections": "Maximum Selections",
    "manager.courseBuilder.coursesPerStudent": "courses per student",
    "manager.courseBuilder.startDate": "Selection Start Date",
    "manager.courseBuilder.endDate": "Selection End Date",
    "manager.courseBuilder.importantNote": "Important Note",
    "manager.courseBuilder.dateRangeNote":
      "Students will only be able to select courses during the specified date range. Make sure to communicate these dates to students in advance.",
    "manager.courseBuilder.searchCourses": "Search courses...",
    "manager.courseBuilder.coursesSelected": "courses selected",
    "manager.courseBuilder.name": "Name",
    "manager.courseBuilder.teacher": "Teacher",
    "manager.courseBuilder.maxStudents": "Max Students",
    "manager.courseBuilder.noCoursesFound": "No courses found matching your search.",
    "manager.courseBuilder.courseSelectionDetails": "Course Selection Details",
    "manager.courseBuilder.notSpecified": "Not specified",
    "manager.courseBuilder.maxSelectionsLabel": "Max Selections:",
    "manager.courseBuilder.selectionPeriod": "Selection Period:",
    "manager.courseBuilder.courses": "Courses:",
    "manager.courseBuilder.selectedCourses": "Selected Courses",
    "manager.courseBuilder.noCoursesSelected": "No Courses Selected",
    "manager.courseBuilder.goBackToAdd": "Go back to add courses to this elective course selection.",
    "manager.courseBuilder.missingInfo": "Missing Information",
    "manager.courseBuilder.semesterRequired": "Semester is required",
    "manager.courseBuilder.yearRequired": "Year is required",
    "manager.courseBuilder.startDateRequired": "Start date is required",
    "manager.courseBuilder.endDateRequired": "End date is required",
    "manager.courseBuilder.courseRequired": "At least one course must be selected",
    "manager.courseBuilder.back": "Back",
    "manager.courseBuilder.next": "Next",
    "manager.courseBuilder.saveAsDraft": "Save as Draft",
    "manager.courseBuilder.publishCourseSelection": "Publish Course Selection",
    "manager.courseBuilder.fall": "Fall",
    "manager.courseBuilder.spring": "Spring",
    "manager.exchangeBuilder.title": "Create Exchange Program",
    "manager.exchangeBuilder.draft": "Draft",
    "manager.exchangeBuilder.step1": "Basic Information",
    "manager.exchangeBuilder.step2": "Add Universities",
    "manager.exchangeBuilder.step3": "Review & Publish",
    "manager.exchangeBuilder.step": "Step",
    "manager.exchangeBuilder.of": "of",
    "manager.exchangeBuilder.programInfo": "Program Information",
    "manager.exchangeBuilder.semester": "Semester",
    "manager.exchangeBuilder.year": "Year",
    "manager.exchangeBuilder.namePreview": "Program Name Preview",
    "manager.exchangeBuilder.selectionRules": "Selection Rules",
    "manager.exchangeBuilder.maxSelections": "Maximum Selections",
    "manager.exchangeBuilder.universitiesPerStudent": "universities per student",
    "manager.exchangeBuilder.startDate": "Selection Start Date",
    "manager.exchangeBuilder.endDate": "Selection End Date",
    "manager.exchangeBuilder.importantNote": "Important Note",
    "manager.exchangeBuilder.dateRangeNote":
      "Students will only be able to select universities during the specified date range. Make sure to communicate these dates to students in advance.",
    "manager.exchangeBuilder.searchUniversities": "Search universities...",
    "manager.exchangeBuilder.universitiesSelected": "universities selected",
    "manager.exchangeBuilder.name": "Name",
    "manager.exchangeBuilder.country": "Country",
    "manager.exchangeBuilder.city": "City",
    "manager.exchangeBuilder.maxStudents": "Max Students",
    "manager.exchangeBuilder.language": "Language",
    "manager.exchangeBuilder.noUniversitiesFound": "No universities found matching your search.",
    "manager.exchangeBuilder.programDetails": "Program Details",
    "manager.exchangeBuilder.notSpecified": "Not specified",
    "manager.exchangeBuilder.maxSelectionsLabel": "Max Selections:",
    "manager.exchangeBuilder.selectionPeriod": "Selection Period:",
    "manager.exchangeBuilder.universities": "Universities:",
    "manager.exchangeBuilder.selectedUniversities": "Selected Universities",
    "manager.exchangeBuilder.noUniversitiesSelected": "No Universities Selected",
    "manager.exchangeBuilder.goBackToAdd": "Go back to add universities to this exchange program.",
    "manager.exchangeBuilder.missingInfo": "Missing Information",
    "manager.exchangeBuilder.semesterRequired": "Semester is required",
    "manager.exchangeBuilder.yearRequired": "Year is required",
    "manager.exchangeBuilder.startDateRequired": "Start date is required",
    "manager.exchangeBuilder.endDateRequired": "End date is required",
    "manager.exchangeBuilder.universityRequired": "At least one university must be selected",
    "manager.exchangeBuilder.back": "Back",
    "manager.exchangeBuilder.next": "Next",
    "manager.exchangeBuilder.saveAsDraft": "Save as Draft",
    "manager.exchangeBuilder.publishProgram": "Publish Program",
    "manager.exchangeBuilder.fall": "Fall",
    "manager.exchangeBuilder.spring": "Spring",
    "manager.courseBuilder.editTitle": "Edit Elective Course Selection",
    "manager.exchangeBuilder.editTitle": "Edit Exchange Program",
    "admin.sidebar.dashboard": "Dashboard",
    "admin.sidebar.electives": "Electives",
    "admin.sidebar.courses": "Courses",
    "admin.sidebar.programs": "Programs",
    "admin.sidebar.groups": "Groups",
    "admin.sidebar.degrees": "Degrees",
    "admin.sidebar.users": "Users",
    "admin.courses.title": "Course Management",
    "admin.courses.subtitle": "Manage elective courses and their assignments",
    "admin.courses.addCourse": "Add Course",
    "admin.courses.search": "Search courses...",
    "admin.courses.status": "Status",
    "admin.courses.allStatus": "All Status",
    "admin.courses.active": "Active",
    "admin.courses.inactive": "Inactive",
    "admin.courses.draft": "Draft",
    "admin.courses.program": "Program",
    "admin.courses.allPrograms": "All Programs",
    "admin.courses.name": "Name",
    "admin.courses.instructor": "Instructor",
    "admin.courses.action": "Action",
    "admin.courses.edit": "Edit",
    "admin.courses.deactivate": "Deactivate",
    "admin.courses.activate": "Activate",
    "admin.courses.delete": "Delete",
    "admin.courses.noCoursesFound": "No courses found.",
    "admin.courses.status.active": "Active",
    "admin.courses.status.inactive": "Inactive",
    "admin.courses.status.draft": "Draft",
    "admin.newCourse.title": "Add New Course",
    "admin.newCourse.nameEn": "Course Name (English)",
    "admin.newCourse.nameRu": "Course Name (Russian)",
    "admin.newCourse.program": "Program",
    "admin.newCourse.selectProgram": "Select a program",
    "admin.newCourse.status": "Status",
    "admin.newCourse.selectStatus": "Select status",
    "admin.newCourse.instructorEn": "Instructor Name (English)",
    "admin.newCourse.instructorRu": "Instructor Name (Russian)",
    "admin.newCourse.descriptionEn": "Description (English)",
    "admin.newCourse.descriptionRu": "Description (Russian)",
    "admin.newCourse.cancel": "Cancel",
    "admin.newCourse.create": "Create Course",
    "admin.newCourse.creating": "Creating...",
    "admin.newCourse.courseDescEn": "Course description in English",
    "admin.newCourse.courseDescRu": "Описание курса на русском языке",
    "manager.exchangeBuilder.editExchangeProgram": "Edit Exchange Program",
    "manager.courseDetails.download": "Download",
    "manager.courseDetails.export": "Export",
    "manager.courseDetails.exportAll": "Export All",
    "manager.exchangeDetails.exportAll": "Export All",
    "manager.exchangeDetails.download": "Download",
    "manager.exchangeDetails.editStudentSelection": "Edit Student Selection",
    "manager.exchangeDetails.editSelectionFor": "Edit selection for",
    "manager.exchangeDetails.editUniversities": "Edit Selected Universities",
    "manager.exchangeDetails.selectUpTo": "Select up to",
    "manager.exchangeDetails.saveChanges": "Save Changes",
    "manager.exchangeDetails.cancel": "Cancel",
    "manager.exchangeDetails.selectionUpdated": "Student selection has been updated successfully",
    "manager.courseDetails.editStudentSelection": "Edit Student Selection",
    "manager.courseDetails.editSelectionFor": "Edit selection for",
    "manager.courseDetails.editCourses": "Edit Selected Courses",
    "manager.courseDetails.selectUpTo": "Select up to",
    "manager.courseDetails.saveChanges": "Save Changes",
    "manager.courseDetails.cancel": "Cancel",
    "manager.courseDetails.selectionUpdated": "Student selection has been updated successfully",
    "manager.courseDetails.withdraw": "Withdraw",
    "manager.exchangeDetails.withdraw": "Withdraw",
    "toast.selection.withdrawn": "Selection withdrawn",
    "toast.selection.withdrawn.description": "The selection for {0} has been withdrawn.",
    "toast.selection.approved": "Selection approved",
    "toast.selection.approved.description": "The selection for {0} has been approved.",
    "toast.selection.rejected": "Selection rejected",
    "toast.selection.rejected.description": "The selection for {0} has been rejected.",
    "toast.selection.updated": "Selection updated successfully",
    "toast.selection.updated.course.description": "The course selection for {0} has been updated.",
    "toast.selection.updated.exchange.description": "The university selection for {0} has been updated.",
    "pagination.previous": "Previous",
    "pagination.next": "Next",
    "pagination.page": "Page",
    "admin.programs.title": "Programs",
    "admin.programs.subtitle": "Manage degree programs and their configurations",
    "admin.programs.addProgram": "Add Program",
    "admin.programs.searchPrograms": "Search programs...",
    "admin.programs.status": "Status",
    "admin.programs.allStatus": "All Status",
    "admin.programs.active": "Active",
    "admin.programs.inactive": "Inactive",
    "admin.programs.level": "Level",
    "admin.programs.allLevels": "All Levels",
    "admin.programs.bachelors": "Bachelor's",
    "admin.programs.masters": "Master's",
    "admin.programs.name": "Name",
    "admin.programs.code": "Code",
    "admin.programs.students": "Students",
    "admin.programs.courses": "Courses",
    "admin.programs.action": "Action",
    "admin.programs.edit": "Edit",
    "admin.programs.viewStudents": "View Students",
    "admin.programs.deactivate": "Deactivate",
    "admin.programs.activate": "Activate",
    "admin.programs.noPrograms": "No programs found.",
    "admin.newProgram.title": "Create New Program",
    "admin.newProgram.programDetails": "Program Details",
    "admin.newProgram.nameEn": "Program Name (English)",
    "admin.newProgram.nameRu": "Program Name (Russian)",
    "admin.newProgram.code": "Program Code",
    "admin.newProgram.codePlaceholder": "A unique code for the program (e.g., MiM, BBA)",
    "admin.newProgram.descriptionEn": "Description (English)",
    "admin.newProgram.descriptionRu": "Description (Russian)",
    "admin.newProgram.degree": "Degree",
    "admin.newProgram.selectDegree": "Select a degree",
    "admin.newProgram.status": "Status",
    "admin.newProgram.cancel": "Cancel",
    "admin.newProgram.create": "Create Program",
    "admin.groups.title": "Student Groups",
    "admin.groups.subtitle": "Manage student groups across all programs and years",
    "admin.groups.addGroup": "Add Group",
    "admin.groups.searchGroups": "Search groups...",
    "admin.groups.filter": "Filter",
    "admin.groups.program": "Program",
    "admin.groups.allPrograms": "All Programs",
    "admin.groups.year": "Year",
    "admin.groups.allYears": "All Years",
    "admin.groups.degree": "Degree",
    "admin.groups.allDegrees": "All Degrees",
    "admin.groups.groupCode": "Group Code",
    "admin.groups.displayName": "Display Name",
    "admin.groups.students": "Students",
    "admin.groups.status": "Status",
    "admin.groups.action": "Action",
    "admin.groups.edit": "Edit",
    "admin.groups.delete": "Delete",
    "admin.groups.deactivate": "Deactivate",
    "admin.groups.activate": "Activate",
    "admin.groups.noGroups": "No groups found",
    "admin.groups.addNewGroup": "Add New Group",
    "admin.groups.editGroup": "Edit Group",
    "admin.groups.groupCodeLabel": "Group Code",
    "admin.groups.groupCodePlaceholder": "e.g., 24.B01-vshm",
    "admin.groups.displayNameLabel": "Display Name",
    "admin.groups.displayNamePlaceholder": "e.g., B01",
    "admin.groups.selectProgram": "Select Program",
    "admin.groups.selectDegree": "Select Degree",
    "admin.groups.selectYear": "Select Year",
    "admin.groups.active": "Active",
    "admin.groups.inactive": "Inactive",
    "admin.groups.cancel": "Cancel",
    "admin.groups.create": "Create",
    "admin.groups.update": "Update",
    "admin.groups.deleteConfirm": "Are you sure you want to delete this group?",
    "admin.degrees.title": "Degree Management",
    "admin.degrees.subtitle": "Manage academic degrees offered by the institution",
    "admin.degrees.addDegree": "Add Degree",
    "admin.degrees.searchDegrees": "Search degrees...",
    "admin.degrees.nameEn": "Name (English)",
    "admin.degrees.nameRu": "Name (Russian)",
    "admin.degrees.code": "Code",
    "admin.degrees.duration": "Duration (Years)",
    "admin.degrees.status": "Status",
    "admin.degrees.action": "Action",
    "admin.degrees.noDegreesFound": "No degrees found",
    "admin.degrees.edit": "Edit",
    "admin.degrees.delete": "Delete",
    "admin.degrees.deactivate": "Deactivate",
    "admin.degrees.activate": "Activate",
    "admin.degrees.addNewDegree": "Add New Degree",
    "admin.degrees.editDegree": "Edit Degree",
    "admin.degrees.cancel": "Cancel",
    "admin.degrees.create": "Create",
    "admin.degrees.update": "Update",
    "admin.degrees.deleteConfirm": "Are you sure you want to delete this degree?",
    "admin.degrees.active": "Active",
    "admin.degrees.inactive": "Inactive",
    "admin.users.title": "User Management",
    "admin.users.subtitle": "Manage all users in the system",
    "admin.users.inviteManager": "Invite Manager",
    "admin.users.inviteStudent": "Invite Student",
    "admin.users.searchUsers": "Search users...",
    "admin.users.role": "Role",
    "admin.users.allRoles": "All Roles",
    "admin.users.status": "Status",
    "admin.users.allStatus": "All Status",
    "admin.users.active": "Active",
    "admin.users.inactive": "Inactive",
    "admin.users.pending": "Pending",
    "admin.users.student": "Student",
    "admin.users.manager": "Manager",
    "admin.users.admin": "Admin",
    "admin.users.name": "Name",
    "admin.users.email": "Email",
    "admin.users.degree": "Degree",
    "admin.users.program": "Program",
    "admin.users.enrollmentYear": "Enrollment Year",
    "admin.users.action": "Action",
    "admin.users.noUsersFound": "No users found",
    "admin.users.edit": "Edit",
    "admin.users.reassignProgram": "Reassign Program",
    "admin.users.deactivate": "Deactivate",
    "admin.users.inviteManagerTitle": "Invite Program Manager",
    "admin.users.fullName": "Full Name",
    "admin.users.emailAddress": "Email Address",
    "admin.users.selectDegree": "Select degree",
    "admin.users.selectProgram": "Select program",
    "admin.users.selectYear": "Select year",
    "admin.users.sendEmailInvitation": "Send email invitation to the program manager",
    "admin.users.emailInvitationInfo": "An email will be sent to {0} with instructions to set up their account.",
    "admin.users.cancel": "Cancel",
    "admin.users.sending": "Sending Invitation...",
    "admin.users.inviteManagerButton": "Invite Manager",
    "admin.users.inviteStudentTitle": "Invite Student",
    "admin.users.sendStudentInvitation": "Send invitation email to the student",
    "admin.users.studentEmailInfo": "An email will be sent to {0} with instructions to set up their account.",
    "admin.users.sendInvitation": "Send Invitation",
    "admin.users.selectDegreeFirst": "Select a degree first",
  },
  ru: {
    "home.title": "Расписание ВШМ",
    "home.subtitle": "Выберите степень, программу, год и группу",
    "timetable.program": "Расписание",
    "timetable.group": "Группа",
    "timetable.return": "Вернуться к выбору",
    "timetable.thisWeek": "Эта неделя",
    "timetable.noClasses": "В этот день занятий не запланировано.",
    "language.switch": "Сменить язык",
    "room.label": "Аудитория",
    "footer.feedback": "Нашли ошибку или хотите предложить улучшение?",
    "footer.gsomStudent": "Разработано студентом ВШМ",
    "footer.telegramMessage": "Отправить сообщение через Telegram",
    "programs.internationalManagement": "Международный менеджмент",
    "programs.management": "Менеджмент",
    "programs.publicAdministration": "Государственное и муниципальное управление",
    "programs.businessAnalytics": "Бизнес-аналитика и большие данные",
    "programs.smartCityManagement": "Управление умным городом",
    "programs.corporateFinance": "Корпоративные финансы",
    "degree.bachelor": "Бакалавриат",
    "degree.master": "Магистратура",
    "year.enrollment": "Год поступления",
    "auth.login.title": "Платформа элективов ВШМ",
    "auth.login.description": "Введите ваши данные для входа в аккаунт",
    "auth.login.email": "Электронная почта",
    "auth.login.password": "Пароль",
    "auth.login.button": "Войти",
    "auth.login.demoText": "Для демонстрации вы также можете:",
    "auth.login.studentDemo": "Демо студента",
    "auth.login.managerDemo": "Демо менеджера",
    "auth.login.adminDemo": "Демо админа",
    "auth.login.noAccount": "Нет аккаунта?",
    "auth.login.signUp": "Зарегистрироваться",
    "auth.signup.title": "Платформа элективов ВШМ",
    "auth.signup.description": "Создайте новый аккаунт с вашей университетской почтой",
    "auth.signup.email": "Электронная почта",
    "auth.signup.emailHint": "Должна заканчиваться на @student.spbu.ru или @gsom.spbu.ru",
    "auth.signup.name": "Полное имя",
    "auth.signup.degree": "Степень",
    "auth.signup.program": "Программа",
    "auth.signup.year": "Год",
    "auth.signup.group": "Группа",
    "auth.signup.password": "Пароль",
    "auth.signup.button": "Зарегистрироваться",
    "auth.signup.hasAccount": "Уже есть аккаунт?",
    "auth.signup.login": "Войти",
    "auth.signup.selectDegree": "Выберите степень",
    "auth.signup.selectProgram": "Выберите программу",
    "auth.signup.selectYear": "Выберите год",
    "auth.signup.selectGroup": "Выберите группу",
    "auth.error.invalidEmail": "Почта должна заканчиваться на @student.spbu.ru или @gsom.spbu.ru",
    "auth.error.incompleteFields": "Пожалуйста, заполните все обязательные поля",
    dashboard: "Панель управления",
    courseSelection: "Выбор курсов",
    exchangeSelection: "Выбор обмена",
    logout: "Выйти",

    // Student Dashboard
    "student.dashboard.title": "Панель управления",
    "student.dashboard.requiredElectives": "Требуемые элективы",
    "student.dashboard.selectedElectives": "Выбранные элективы",
    "student.dashboard.pendingSelections": "Ожидающие выборы",
    "student.dashboard.courses": "курсов",
    "student.dashboard.exchange": "программ обмена",
    "student.dashboard.yourInfo": "Ваша информация",
    "student.dashboard.academicDetails": "Ваши академические данные",
    "student.dashboard.name": "Имя",
    "student.dashboard.degree": "Степень",
    "student.dashboard.program": "Программа",
    "student.dashboard.yearEnrollment": "Год поступления",
    "student.dashboard.group": "Группа",
    "student.dashboard.email": "Электронная почта",
    "student.dashboard.upcomingDeadlines": "Предстоящие сроки",
    "student.dashboard.importantDates": "Важные даты для выбора элективов",
    "student.dashboard.daysLeft": "дней осталось",

    // Student Courses
    "student.dashboard.upcomingDeadlines": "Предстоящие сроки",
    "student.dashboard.importantDates": "Важные даты для выбора элективов",
    "student.dashboard.daysLeft": "дней осталось",

    // Student Courses
    "student.courses.title": "Выбор курсов",
    "student.courses.subtitle": "Просмотр и выбор элективных курсов, доступных в семестре для вашей программы",
    "student.courses.deadline": "Срок",
    "student.courses.courses": "Курсы",
    "student.courses.limit": "Лимит",
    "student.courses.selected": "Выбрано",
    "student.courses.view": "Просмотр",
    "student.courses.noSelection": "Нет выбора",
    "student.courses.comingSoon": "Скоро",
    "student.courses.open": "Открыто",
    "student.courses.limited": "Ограничено",
    "student.courses.selectCourses": "Выберите элективные курсы на этот семестр",
    "student.courses.selectionProgress": "Прогресс выбора",
    "student.courses.selectedOutOf": "Вы выбрали",
    "student.courses.allowedCourses": "разрешенных курсов",
    "student.courses.maxSelections": "Вы достигли максимального количества выборов",
    "student.courses.canSelectMore": "Вы можете выбрать еще",
    "student.courses.moreCourse": "курс",
    "student.courses.moreCourses": "курсов",
    "student.courses.selectionApproved": "Выбор утвержден",
    "student.courses.selectionApprovedDesc":
      "Ваш выбор элективных курсов был утвержден. Вы можете просмотреть выбранные курсы ниже.",
    "student.courses.selectionPending": "Выбор на рассмотрении",
    "student.courses.selectionPendingDesc":
      "Ваш выбор элективных курсов находится на рассмотрении. Вы все еще можете изменить свой выбор до истечения срока.",
    "student.courses.selectionPeriodActive": "Период выбора активен",
    "student.courses.selectionPeriodDesc": "Вы можете выбрать до",
    "student.courses.until": "до",
    "student.courses.viewDescription": "Просмотреть описание",
    "student.courses.select": "Выбрать",
    "student.courses.updateSelection": "Обновить выбор",
    "student.courses.confirmSelection": "Подтвердить выбор",
    "student.courses.confirmYourSelection": "Подтвердите ваш выбор",
    "student.courses.reviewSelection":
      "Пожалуйста, проверьте ваш выбор и введите ваше полное имя для авторизации этой заявки.",
    "student.courses.selectedCourses": "Выбранные курсы",
    "student.courses.credits": "кредитов",
    "student.courses.yourFullName": "Ваше полное имя",
    "student.courses.toAuthorize": "для авторизации",
    "student.courses.enterFullName": "Введите ваше полное имя",
    "student.courses.submitting": "Отправка...",
    "student.courses.submitSelection": "Отправить выбор",
    "student.courses.courseDescription": "Описание курса",
    "student.courses.close": "Закрыть",
    "student.courses.removeSelection": "Удалить выбор",
    "student.courses.selectCourse": "Выбрать курс",

    // Student Exchange
    "student.exchange.title": "Выбор программы обмена",
    "student.exchange.subtitle": "Просмотр и выбор университетов обмена, доступных для вашей программы",
    "student.exchange.deadline": "Срок",
    "student.exchange.universities": "Университеты",
    "student.exchange.limit": "Лимит",
    "student.exchange.selected": "Выбрано",
    "student.exchange.view": "Просмотр",
    "student.exchange.noSelection": "Нет выбора",
    "student.exchange.comingSoon": "Скоро",
    "student.exchange.open": "Открыто",
    "student.exchange.limited": "Ограничено",
    "student.exchange.selectUniversities": "Выберите университеты обмена на этот семестр",
    "student.exchange.selectionProgress": "Прогресс выбора",
    "student.exchange.selectedOutOf": "Вы выбрали",
    "student.exchange.allowedUniversities": "разрешенных университетов",
    "student.exchange.maxSelections": "Вы достигли максимального количества выборов",
    "student.exchange.canSelectMore": "Вы можете выбрать еще",
    "student.exchange.moreUniversity": "университет",
    "student.exchange.moreUniversities": "университетов",
    "student.exchange.selectionApproved": "Выбор утвержден",
    "student.exchange.selectionApprovedDesc":
      "Ваш выбор университетов обмена был утвержден. Вы можете просмотреть выбранные университеты ниже.",
    "student.exchange.selectionPending": "Выбор на рассмотрении",
    "student.exchange.selectionPendingDesc":
      "Ваш выбор университетов обмена находится на рассмотрении. Вы все еще можете изменить свой выбор до истечения срока.",
    "student.exchange.selectionPeriodActive": "Период выбора активен",
    "student.exchange.selectionPeriodDesc": "Вы можете выбрать до",
    "student.exchange.until": "до",
    "student.exchange.viewDetails": "Просмотреть детали",
    "student.exchange.select": "Выбрать",
    "student.exchange.updateSelection": "Обновить выбор",
    "student.exchange.confirmSelection": "Подтвердить выбор",
    "student.exchange.confirmYourSelection": "Подтвердите ваш выбор",
    "student.exchange.reviewSelection":
      "Пожалуйста, проверьте ваш выбор и введите ваше полное имя для авторизации этой заявки.",
    "student.exchange.selectedUniversities": "Выбранные университеты",
    "student.exchange.yourFullName": "Ваше полное имя",
    "student.exchange.toAuthorize": "для авторизации",
    "student.exchange.enterFullName": "Введите ваше полное имя",
    "student.exchange.submitting": "Отправка...",
    "student.exchange.submitSelection": "Отправить выбор",
    "student.exchange.universityDescription": "Описание университета",
    "student.exchange.languageInstruction": "Язык обучения",
    "student.exchange.availablePrograms": "Доступные программы",
    "student.exchange.close": "Закрыть",
    "student.exchange.visitWebsite": "Посетить сайт",
    "student.exchange.comingSoonDesc":
      "Выбор обмена еще не открыт. Вы можете просмотреть доступные университеты, но выбор будет доступен начиная с",

    // Manager Dashboard
    "manager.dashboard.title": "Панель управления",
    "manager.dashboard.courseElectives": "Пакеты элективов",
    "manager.dashboard.totalCourseElectives": "Всего выборов элективных курсов",
    "manager.dashboard.manageCourseElectives": "Управление элективными курсами",
    "manager.dashboard.exchangePrograms": "Программы обмена",
    "manager.dashboard.totalExchangePrograms": "Всего доступных программ обмена",
    "manager.dashboard.manageExchangePrograms": "Управление программами обмена",
    "manager.dashboard.yourInformation": "Ваша информация",
    "manager.dashboard.managerDetails": "Данные менеджера программы",
    "manager.dashboard.name": "Имя",
    "manager.dashboard.program": "Программа",
    "manager.dashboard.degree": "Степень",
    "manager.dashboard.year": "Год",
    "manager.dashboard.email": "Электронная почта",
    "manager.dashboard.upcomingDeadlines": "Предстоящие сроки",
    "manager.dashboard.importantDates": "Важные даты для элективов",
    "manager.dashboard.daysLeft": "дней осталось",

    // Manager Electives
    "manager.electives.title": "Пакеты элективов",
    "manager.electives.subtitle": "Управление выбором элективных курсов и программ обмена",
    "manager.electives.courseElectives": "Элективные курсы",
    "manager.electives.exchangePrograms": "Программы обмена",
    "manager.electives.create": "Создать",
    "manager.electives.searchCourses": "Поиск элективных курсов...",
    "manager.electives.searchExchange": "Поиск программ обмена...",
    "manager.electives.program": "Программа",
    "manager.electives.allPrograms": "Все программы",
    "manager.electives.semester": "Семестр",
    "manager.electives.allSemesters": "Все семестры",
    "manager.electives.status": "Статус",
    "manager.electives.allStatus": "Все статусы",
    "manager.electives.active": "Активный",
    "manager.electives.inactive": "Неактивный",
    "manager.electives.draft": "Черновик",
    "manager.electives.deadline": "Срок",
    "manager.electives.courses": "Курсы",
    "manager.electives.selections": "Выборы",
    "manager.electives.createdBy": "Создано",
    "manager.electives.on": "от",
    "manager.electives.viewDetails": "Просмотр деталей",
    "manager.electives.noCourseElectives": "Элективные курсы не найдены.",
    "manager.electives.createNewElectivePack": "Создать новый пакет элективов",
    "manager.electives.universities": "Университеты",
    "manager.electives.noExchangePrograms": "Программы обмена не найдены.",
    "manager.electives.createNewExchangeProgram": "Создать новую программу обмена",
    "manager.electives.edit": "Редактировать",
    "manager.electives.exportData": "Экспорт данных",
    "manager.exchangeBuilder.statementUpload": "Загрузка заявления",
    "manager.exchangeBuilder.uploadStatementFile": "Загрузить файл заявления (PDF)",
    "manager.exchangeBuilder.statementDescription":
      "Загрузите пустой файл заявления, который студенты скачают, подпишут и загрузят обратно.",
    "student.statement.title": "Форма заявления",
    "student.statement.description": "Скачайте заявление, подпишите его и загрузите заполненную форму",
    "student.statement.download": "Скачать",
    "student.statement.uploading": "Загрузка...",
    "student.statement.fileUploaded": "Файл загружен:",

    // Manager Exchange Details
    "manager.exchangeDetails.backToElectives": "Назад к элективам",
    "manager.exchangeDetails.edit": "Редактировать",
    "manager.exchangeDetails.programDetails": "Детали программы",
    "manager.exchangeDetails.selectionPeriod": "Период выбора",
    "manager.exchangeDetails.maxSelections": "Максимальное количество выборов",
    "manager.exchangeDetails.universities": "университетов",
    "manager.exchangeDetails.studentsEnrolled": "Зачисленные студенты",
    "manager.exchangeDetails.created": "Создано",
    "manager.exchangeDetails.status": "Статус",
    "manager.exchangeDetails.universitiesTab": "Университеты",
    "manager.exchangeDetails.studentsTab": "Выборы студентов",
    "manager.exchangeDetails.name": "Название",
    "manager.exchangeDetails.location": "Местоположение",
    "manager.exchangeDetails.language": "Язык",
    "manager.exchangeDetails.enrollment": "Зачисление",
    "manager.exchangeDetails.studentSelections": "Выборы студентов",
    "manager.exchangeDetails.manageStudentSelections": "Управление выборами студентов для этой программы обмена",
    "manager.exchangeDetails.searchStudents": "Поиск студентов...",
    "manager.exchangeDetails.export": "Экспорт",
    "manager.exchangeDetails.group": "Группа",
    "manager.exchangeDetails.selectionDate": "Дата выбора",
    "manager.exchangeDetails.view": "Просмотр",
    "manager.exchangeDetails.actions": "Действия",
    "manager.exchangeDetails.approved": "Утверждено",
    "manager.exchangeDetails.pending": "На рассмотрении",
    "manager.exchangeDetails.rejected": "Отклонено",
    "manager.exchangeDetails.approve": "Утвердить",
    "manager.exchangeDetails.reject": "Отклонить",
    "manager.exchangeDetails.studentDetails": "Детали выбора студента",
    "manager.exchangeDetails.viewDetailsFor": "Просмотр деталей для",
    "manager.exchangeDetails.exchangeSelection": "выбора обмена",
    "manager.exchangeDetails.studentInformation": "Информация о студенте",
    "manager.exchangeDetails.id": "ID",
    "manager.exchangeDetails.email": "Электронная почта",
    "manager.exchangeDetails.program": "Программа",
    "manager.exchangeDetails.selectedUniversities": "Выбранные университеты",
    "manager.exchangeDetails.selectionInformation": "Информация о выборе",
    "manager.exchangeDetails.date": "Дата",
    "manager.exchangeDetails.close": "Закрыть",
    "manager.status.draft": "Черновик",
    "manager.status.published": "Опубликовано",
    "manager.status.closed": "Закрыто",
    "manager.status.archived": "В архиве",
    "manager.courseDetails.title": "Детали курса",
    "manager.courseDetails.backToElectives": "Назад к элективам",
    "manager.courseDetails.edit": "Редактировать",
    "manager.courseDetails.programDetails": "Детали программы",
    "manager.courseDetails.selectionPeriod": "Период выбора",
    "manager.courseDetails.maxSelections": "Максимальное количество выборов",
    "manager.courseDetails.courses": "курсов",
    "manager.courseDetails.studentsEnrolled": "Зачисленные студенты",
    "manager.courseDetails.created": "Создано",
    "manager.courseDetails.status": "Статус",
    "manager.courseDetails.coursesTab": "Курсы",
    "manager.courseDetails.studentsTab": "Выборы студентов",
    "manager.courseDetails.coursesInProgram": "Курсы в этой программе",
    "manager.courseDetails.name": "Название",
    "manager.courseDetails.professor": "Преподаватель",
    "manager.courseDetails.credits": "Кредиты",
    "manager.courseDetails.enrollment": "Зачисление",
    "manager.courseDetails.studentSelections": "Выборы студентов",
    "manager.courseDetails.manageStudentSelections": "Управление выборами студентов для этой программы элективов",
    "manager.courseDetails.searchStudents": "Поиск студентов...",
    "manager.courseDetails.export": "Экспорт",
    "manager.courseDetails.group": "Группа",
    "manager.courseDetails.selectionDate": "Дата выбора",
    "manager.courseDetails.view": "Просмотр",
    "manager.courseDetails.actions": "Действия",
    "manager.courseDetails.studentDetails": "Детали выбора студента",
    "manager.courseDetails.viewDetailsFor": "Просмотр деталей для",
    "manager.courseDetails.courseSelection": "выбора курсов",
    "manager.courseDetails.studentInformation": "Информация о студенте",
    "manager.courseDetails.id": "ID",
    "manager.courseDetails.email": "Электронная почта",
    "manager.courseDetails.program": "Программа",
    "manager.courseDetails.selectedCourses": "Выбранные курсы",
    "manager.courseDetails.selectionInformation": "Информация о выборе",
    "manager.courseDetails.date": "Дата",
    "manager.courseDetails.close": "Закрыть",
    "manager.courseBuilder.title": "Создание выбора элективных курсов",
    "manager.courseBuilder.draft": "Черновик",
    "manager.courseBuilder.step1": "Основная информация",
    "manager.courseBuilder.step2": "Добавление курсов",
    "manager.courseBuilder.step3": "Просмотр и публикация",
    "manager.courseBuilder.step": "Шаг",
    "manager.courseBuilder.of": "из",
    "manager.courseBuilder.courseInfo": "Информация о выборе курсов",
    "manager.courseBuilder.semester": "Семестр",
    "manager.courseBuilder.year": "Год",
    "manager.courseBuilder.namePreview": "Предварительный просмотр названия выбора курсов",
    "manager.courseBuilder.selectionRules": "Правила выбора",
    "manager.courseBuilder.maxSelections": "Максимальное количество выборов",
    "manager.courseBuilder.coursesPerStudent": "курсов на студента",
    "manager.courseBuilder.startDate": "Дата начала выбора",
    "manager.courseBuilder.endDate": "Дата окончания выбора",
    "manager.courseBuilder.importantNote": "Важное примечание",
    "manager.courseBuilder.dateRangeNote":
      "Студенты смогут выбирать курсы только в указанный период. Убедитесь, что вы заранее сообщили эти даты студентам.",
    "manager.courseBuilder.searchCourses": "Поиск курсов...",
    "manager.courseBuilder.coursesSelected": "выбрано курсов",
    "manager.courseBuilder.name": "Название",
    "manager.courseBuilder.teacher": "Преподаватель",
    "manager.courseBuilder.maxStudents": "Макс. студентов",
    "manager.courseBuilder.noCoursesFound": "Не найдено курсов, соответствующих вашему запросу.",
    "manager.courseBuilder.courseSelectionDetails": "Детали выбора курсов",
    "manager.courseBuilder.notSpecified": "Не указано",
    "manager.courseBuilder.maxSelectionsLabel": "Макс. выборов:",
    "manager.courseBuilder.selectionPeriod": "Период выбора:",
    "manager.courseBuilder.courses": "Курсы:",
    "manager.courseBuilder.selectedCourses": "Выбранные курсы",
    "manager.courseBuilder.noCoursesSelected": "Курсы не выбраны",
    "manager.courseBuilder.goBackToAdd": "Вернитесь назад, чтобы добавить курсы в этот выбор элективных курсов.",
    "manager.courseBuilder.missingInfo": "Отсутствующая информация",
    "manager.courseBuilder.semesterRequired": "Требуется указать семестр",
    "manager.courseBuilder.yearRequired": "Требуется указать год",
    "manager.courseBuilder.startDateRequired": "Требуется указать дату начала",
    "manager.courseBuilder.endDateRequired": "Требуется указать дату окончания",
    "manager.courseBuilder.courseRequired": "Необходимо выбрать хотя бы один курс",
    "manager.courseBuilder.back": "Назад",
    "manager.courseBuilder.next": "Далее",
    "manager.courseBuilder.saveAsDraft": "Сохранить как черновик",
    "manager.courseBuilder.publishCourseSelection": "Опубликовать выбор курсов",
    "manager.courseBuilder.fall": "Осенний",
    "manager.courseBuilder.spring": "Весенний",
    "manager.exchangeBuilder.title": "Создание программы обмена",
    "manager.exchangeBuilder.draft": "Черновик",
    "manager.exchangeBuilder.step1": "Основная информация",
    "manager.exchangeBuilder.step2": "Добавление университетов",
    "manager.exchangeBuilder.step3": "Просмотр и публикация",
    "manager.exchangeBuilder.step": "Шаг",
    "manager.exchangeBuilder.of": "из",
    "manager.exchangeBuilder.programInfo": "Информация о программе",
    "manager.exchangeBuilder.semester": "Семестр",
    "manager.exchangeBuilder.year": "Год",
    "manager.exchangeBuilder.namePreview": "Предварительный просмотр названия программы",
    "manager.exchangeBuilder.selectionRules": "Правила выбора",
    "manager.exchangeBuilder.maxSelections": "Максимальное количество выборов",
    "manager.exchangeBuilder.universitiesPerStudent": "университетов на студента",
    "manager.exchangeBuilder.startDate": "Дата начала выбора",
    "manager.exchangeBuilder.endDate": "Дата окончания выбора",
    "manager.exchangeBuilder.importantNote": "Важное примечание",
    "manager.exchangeBuilder.dateRangeNote":
      "Студенты смогут выбирать университеты только в указанный период. Убедитесь, что вы заранее сообщили эти даты студентам.",
    "manager.exchangeBuilder.searchUniversities": "Поиск университетов...",
    "manager.exchangeBuilder.universitiesSelected": "выбрано университетов",
    "manager.exchangeBuilder.name": "Название",
    "manager.exchangeBuilder.country": "Страна",
    "manager.exchangeBuilder.city": "Город",
    "manager.exchangeBuilder.maxStudents": "Макс. студентов",
    "manager.exchangeBuilder.language": "Язык",
    "manager.exchangeBuilder.noUniversitiesFound": "Не найдено университетов, соответствующих вашему запросу.",
    "manager.exchangeBuilder.programDetails": "Детали программы",
    "manager.exchangeBuilder.notSpecified": "Не указано",
    "manager.exchangeBuilder.maxSelectionsLabel": "Макс. выборов:",
    "manager.exchangeBuilder.selectionPeriod": "Период выбора:",
    "manager.exchangeBuilder.universities": "Университеты:",
    "manager.exchangeBuilder.selectedUniversities": "Выбранные университеты",
    "manager.exchangeBuilder.noUniversitiesSelected": "Университеты не выбраны",
    "manager.exchangeBuilder.goBackToAdd": "Вернитесь назад, чтобы добавить университеты в эту программу обмена.",
    "manager.exchangeBuilder.missingInfo": "Отсутствующая информация",
    "manager.exchangeBuilder.semesterRequired": "Требуется указать семестр",
    "manager.exchangeBuilder.yearRequired": "Требуется указать год",
    "manager.exchangeBuilder.startDateRequired": "Требуется указать дату начала",
    "manager.exchangeBuilder.endDateRequired": "Требуется указать дату окончания",
    "manager.exchangeBuilder.universityRequired": "Необходимо выбрать хотя бы один университет",
    "manager.exchangeBuilder.back": "Назад",
    "manager.exchangeBuilder.next": "Далее",
    "manager.exchangeBuilder.saveAsDraft": "Сохранить как черновик",
    "manager.exchangeBuilder.publishProgram": "Опубликовать программу",
    "manager.exchangeBuilder.fall": "Осенний",
    "manager.exchangeBuilder.spring": "Весенний",
    "manager.courseBuilder.editTitle": "Редактирование выбора элективных курсов",
    "manager.exchangeBuilder.editTitle": "Редактировать программу обмена",
    "admin.sidebar.dashboard": "Панель управления",
    "admin.sidebar.electives": "Элективы",
    "admin.sidebar.courses": "Курсы",
    "admin.sidebar.programs": "Программы",
    "admin.sidebar.groups": "Группы",
    "admin.sidebar.degrees": "Степени",
    "admin.sidebar.users": "Пользователи",
    "admin.courses.title": "Управление курсами",
    "admin.courses.subtitle": "Управление элективными курсами и их назначениями",
    "admin.courses.addCourse": "Добавить курс",
    "admin.courses.search": "Поиск курсов...",
    "admin.courses.status": "Статус",
    "admin.courses.allStatus": "Все статусы",
    "admin.courses.active": "Активный",
    "admin.courses.inactive": "Неактивный",
    "admin.courses.draft": "Черновик",
    "admin.courses.program": "Программа",
    "admin.courses.allPrograms": "Все программы",
    "admin.courses.name": "Название",
    "admin.courses.instructor": "Преподаватель",
    "admin.courses.action": "Действие",
    "admin.courses.edit": "Редактировать",
    "admin.courses.deactivate": "Деактивировать",
    "admin.courses.activate": "Активировать",
    "admin.courses.delete": "Удалить",
    "admin.courses.noCoursesFound": "Курсы не найдены.",
    "admin.courses.status.active": "Активный",
    "admin.courses.status.inactive": "Неактивный",
    "admin.courses.status.draft": "Черновик",

    "admin.newCourse.title": "Добавить новый курс",
    "admin.newCourse.nameEn": "Название курса (английский)",
    "admin.newCourse.nameRu": "Название курса (русский)",
    "admin.newCourse.program": "Программа",
    "admin.newCourse.selectProgram": "Выберите программу",
    "admin.newCourse.status": "Статус",
    "admin.newCourse.selectStatus": "Выберите статус",
    "admin.newCourse.instructorEn": "Имя преподавателя (английский)",
    "admin.newCourse.instructorRu": "Имя преподавателя (русский)",
    "admin.newCourse.descriptionEn": "Описание (английский)",
    "admin.newCourse.descriptionRu": "Описание (русский)",
    "admin.newCourse.cancel": "Отмена",
    "manager.courseDetails.withdraw": "Отозвать",
    "manager.exchangeDetails.withdraw": "Отозвать",
    "toast.selection.withdrawn": "Выбор отозван",
    "toast.selection.withdrawn.description": "Выбор для {0} был отозван.",
    "toast.selection.approved": "Выбор утвержден",
    "toast.selection.approved.description": "Выбор для {0} был утвержден.",
    "toast.selection.rejected": "Выбор отклонен",
    "toast.selection.rejected.description": "Выбор для {0} был отклонен.",
    "toast.selection.updated": "Выбор успешно обновлен",
    "toast.selection.updated.course.description": "Выбор курсов для {0} был обновлен.",
    "toast.selection.updated.exchange.description": "Выбор университетов для {0} был обновлен.",
    "pagination.previous": "Предыдущая",
    "pagination.next": "Следующая",
    "pagination.page": "Страница",
    "admin.programs.title": "Программы",
    "admin.programs.subtitle": "Управление программами обучения и их конфигурациями",
    "admin.programs.addProgram": "Добавить программу",
    "admin.programs.searchPrograms": "Поиск программ...",
    "admin.programs.status": "Статус",
    "admin.programs.allStatus": "Все статусы",
    "admin.programs.active": "Активная",
    "admin.programs.inactive": "Неактивная",
    "admin.programs.level": "Уровень",
    "admin.programs.allLevels": "Все уровни",
    "admin.programs.bachelors": "Бакалавриат",
    "admin.programs.masters": "Магистратура",
    "admin.programs.name": "Название",
    "admin.programs.code": "Код",
    "admin.programs.students": "Студенты",
    "admin.programs.courses": "Курсы",
    "admin.programs.action": "Действие",
    "admin.programs.edit": "Редактировать",
    "admin.programs.viewStudents": "Просмотр студентов",
    "admin.programs.deactivate": "Деактивировать",
    "admin.programs.activate": "Активировать",
    "admin.programs.noPrograms": "Программы не найдены.",
    "admin.newProgram.title": "Создание новой программы",
    "admin.newProgram.programDetails": "Детали программы",
    "admin.newProgram.nameEn": "Название программы (английский)",
    "admin.newProgram.nameRu": "Название программы (русский)",
    "admin.newProgram.code": "Код программы",
    "admin.newProgram.codePlaceholder": "Уникальный код программы (например, MiM, BBA)",
    "admin.newProgram.descriptionEn": "Описание (английский)",
    "admin.newProgram.descriptionRu": "Описание (русский)",
    "admin.newProgram.degree": "Степень",
    "admin.newProgram.selectDegree": "Выберите степень",
    "admin.newProgram.status": "Статус",
    "admin.newProgram.cancel": "Отмена",
    "admin.newProgram.create": "Создать программу",
    "admin.groups.title": "Студенческие группы",
    "admin.groups.subtitle": "Управление студенческими группами по всем программам и годам",
    "admin.groups.addGroup": "Добавить группу",
    "admin.groups.searchGroups": "Поиск групп...",
    "admin.groups.filter": "Фильтр",
    "admin.groups.program": "Программа",
    "admin.groups.allPrograms": "Все программы",
    "admin.groups.year": "Год",
    "admin.groups.allYears": "Все годы",
    "admin.groups.degree": "Степень",
    "admin.groups.allDegrees": "Все степени",
    "admin.groups.groupCode": "Код группы",
    "admin.groups.displayName": "Отображаемое имя",
    "admin.groups.students": "Студенты",
    "admin.groups.status": "Статус",
    "admin.groups.action": "Действие",
    "admin.groups.edit": "Редактировать",
    "admin.groups.delete": "Удалить",
    "admin.groups.deactivate": "Деактивировать",
    "admin.groups.activate": "Активировать",
    "admin.groups.noGroups": "Группы не найдены",
    "admin.groups.addNewGroup": "Добавить новую группу",
    "admin.groups.editGroup": "Редактировать группу",
    "admin.groups.groupCodeLabel": "Код группы",
    "admin.groups.groupCodePlaceholder": "например, 24.B01-vshm",
    "admin.groups.displayNameLabel": "Отображаемое имя",
    "admin.groups.displayNamePlaceholder": "например, B01",
    "admin.groups.selectProgram": "Выберите программу",
    "admin.groups.selectDegree": "Выберите степень",
    "admin.groups.selectYear": "Выберите год",
    "admin.groups.active": "Активная",
    "admin.groups.inactive": "Неактивная",
    "admin.groups.cancel": "Отмена",
    "admin.groups.create": "Создать",
    "admin.groups.update": "Обновить",
    "admin.groups.deleteConfirm": "Вы уверены, что хотите удалить эту степень?",
    "admin.degrees.title": "Управление степенями",
    "admin.degrees.subtitle": "Управление академическими степенями, предлагаемыми учреждением",
    "admin.degrees.addDegree": "Добавить степень",
    "admin.degrees.searchDegrees": "Поиск степеней...",
    "admin.degrees.nameEn": "Название (английский)",
    "admin.degrees.nameRu": "Название (русский)",
    "admin.degrees.code": "Код",
    "admin.degrees.duration": "Продолжительность (лет)",
    "admin.degrees.status": "Статус",
    "admin.degrees.action": "Действие",
    "admin.degrees.noDegreesFound": "Степени не найдены",
    "admin.degrees.edit": "Редактировать",
    "admin.degrees.delete": "Удалить",
    "admin.degrees.deactivate": "Деактивировать",
    "admin.degrees.activate": "Активировать",
    "admin.degrees.addNewDegree": "Добавить новую степень",
    "admin.degrees.editDegree": "Редактировать степень",
    "admin.degrees.cancel": "Отмена",
    "admin.degrees.create": "Создать",
    "admin.degrees.update": "Обновить",
    "admin.degrees.deleteConfirm": "Вы уверены, что хотите удалить эту степень?",
    "admin.degrees.active": "Активная",
    "admin.degrees.inactive": "Неактивная",
    "admin.users.title": "Управление пользователями",
    "admin.users.subtitle": "Управление всеми пользователями в системе",
    "admin.users.inviteManager": "Пригласить менеджера",
    "admin.users.inviteStudent": "Пригласить студента",
    "admin.users.searchUsers": "Поиск пользователей...",
    "admin.users.role": "Роль",
    "admin.users.allRoles": "Все роли",
    "admin.users.status": "Статус",
    "admin.users.allStatus": "Все статусы",
    "admin.users.active": "Активный",
    "admin.users.inactive": "Неактивный",
    "admin.users.pending": "Ожидает",
    "admin.users.student": "Студент",
    "admin.users.manager": "Менеджер",
    "admin.users.admin": "Админ",
    "admin.users.name": "Имя",
    "admin.users.email": "Электронная почта",
    "admin.users.degree": "Степень",
    "admin.users.program": "Программа",
    "admin.users.enrollmentYear": "Год поступления",
    "admin.users.action": "Действие",
    "admin.users.noUsersFound": "Пользователи не найдены",
    "admin.users.edit": "Редактировать",
    "admin.users.reassignProgram": "Переназначить программу",
    "admin.users.deactivate": "Деактивировать",
    "admin.users.inviteManagerTitle": "Пригласить менеджера программы",
    "admin.users.fullName": "Полное имя",
    "admin.users.emailAddress": "Электронная почта",
    "admin.users.selectDegree": "Выберите степень",
    "admin.users.selectProgram": "Выберите программу",
    "admin.users.selectYear": "Выберите год",
    "admin.users.sendEmailInvitation": "Отправить приглашение по электронной почте менеджеру",
    "admin.users.emailInvitationInfo":
      "Электронное письмо будет отправлено на адрес {0} с инструкциями по настройке учетной записи.",
    "admin.users.cancel": "Отмена",
    "admin.users.sending": "Отправка приглашения...",
    "admin.users.inviteManagerButton": "Пригласить менеджера",
    "admin.users.inviteStudentTitle": "Пригласить студента",
    "admin.users.sendStudentInvitation": "Отправить приглашение по электронной почте студенту",
    "admin.users.studentEmailInfo":
      "Электронное письмо будет отправлено на адрес {0} с инструкциями по настройке учетной записи.",
    "admin.users.sendInvitation": "Отправить приглашение",
    "admin.users.selectDegreeFirst": "Сначала выберите степень",
  },
}

// Helper function to detect browser language
const detectBrowserLanguage = (): "en" | "ru" => {
  if (typeof window === "undefined") return "en" // Default for SSR

  const browserLang = navigator.language.toLowerCase().split("-")[0]
  return browserLang === "ru" ? "ru" : "en"
}

// Helper function to get stored language preference
const getStoredLanguage = (): "en" | "ru" | null => {
  if (typeof window === "undefined") return null // Return null for SSR

  try {
    const storedLang = localStorage.getItem(LANGUAGE_STORAGE_KEY)
    return storedLang === "ru" ? "ru" : storedLang === "en" ? "en" : null
  } catch (error) {
    console.error("Error accessing localStorage:", error)
    return null
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Initialize with a placeholder, will be updated in useEffect
  const [language, setLanguageState] = useState<"en" | "ru">("en")
  const [isInitialized, setIsInitialized] = useState(false)

  // Custom setter that also updates localStorage
  const setLanguage = useCallback((newLanguage: "en" | "ru") => {
    setLanguageState(newLanguage)
    try {
      localStorage.setItem(LANGUAGE_STORAGE_KEY, newLanguage)
    } catch (error) {
      console.error("Error setting localStorage:", error)
    }
  }, [])

  // Initialize language based on stored preference or browser language
  useEffect(() => {
    if (!isInitialized) {
      const storedLang = getStoredLanguage()
      const initialLang = storedLang || detectBrowserLanguage()
      setLanguageState(initialLang)
      setIsInitialized(true)
    }
  }, [isInitialized])

  const t = useCallback(
    (key: string) => {
      const dict = translations[language] || translations.en
      return dict[key] || key
    },
    [language],
  )

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
